// Generates public/sw.js with a cache version injected from CATALOG_DATE.
// Runs in the build pipeline (see package.json "prebuild" + "build") so it
// executes on Vercel as well as locally — a new GTM date auto-purges old cache.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const catalog = readFileSync(join(root, "data", "catalog.ts"), "utf8");
const match = catalog.match(/CATALOG_DATE\s*=\s*"([^"]+)"/);
const version = match ? match[1] : "0";

const sw = `// AUTO-GENERATED by scripts/gen-sw.mjs — do not edit by hand.
// Cache version is injected from CATALOG_DATE: a new GTM => new key => old cache purged.
const CACHE = "maxis-${version}";
const SHELL = ["/", "/manifest.webmanifest"];

self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL)).catch(() => {}));
  self.skipWaiting();
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (e) => {
  if (e.request.method !== "GET") return;
  // HTML: network-first so a fresh app shell always wins; fall back to cache offline.
  if (e.request.mode === "navigate") {
    e.respondWith(
      fetch(e.request)
        .then((r) => { const cp = r.clone(); caches.open(CACHE).then((c) => c.put("/", cp)); return r; })
        .catch(() => caches.match("/"))
    );
    return;
  }
  // Static assets: cache-first (fast, works offline), then fill cache on miss.
  e.respondWith(
    caches.match(e.request).then((cached) =>
      cached ||
      fetch(e.request).then((resp) => {
        if (resp.ok && e.request.url.startsWith(self.location.origin)) {
          const cp = resp.clone();
          caches.open(CACHE).then((c) => c.put(e.request, cp));
        }
        return resp;
      }).catch(() => cached)
    )
  );
});
`;

writeFileSync(join(root, "public", "sw.js"), sw);
console.log(`[gen-sw] wrote public/sw.js  (CACHE = maxis-${version})`);
